#!/bin/bash
#
# douane      This shell script takes care of starting and stopping
#             douane service (A modern firewall at application layer)
#
# Author: qbyss (qbyss@spher.net)
#
# description: douane is the service of the Douane firewall application. \
# This firewall is limiting access to the internet on application bases.

# Source function library.
. /lib/lsb/init-functions

NAME=douaned
DOUANEDIR=/opt/douane
SERVICE=$DOUANEDIR/$NAME
PIDDIR=/var/run/
PIDFILE=$PIDDIR/$NAME.pid
DOUANEOPTIONS="-D"

start()
{
    echo $"Starting the $NAME service..."
    # Checking if the kernel module is loaded into memory
    [[ -z "$(lsmod | grep douane)" ]] && modprobe douane
    # Creating the pids folder if not existing
    if [ ! -e $PIDDIR ]; then
        mkdir $PIDDIR
        chown root $PIDDIR
    fi

    # TODO: Find a better way to start service on fedora
    $SERVICE $DOUANEOPTIONS & echo $! > $PIDFILE
}

stop()
{
  echo $"Stopping $NAME service..."
  kill `cat $PIDFILE`

  # Remove PID file fs remaining
  [[ -a $PIDFILE ]] && rm $PIDFILE
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:  {start|stop|restart}"
        exit 1
        ;;
esac
exit $?
