
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__org_zedroot_douane_proxy_h__PROXY_MARSHAL_H
#define __dbusxx__org_zedroot_douane_proxy_h__PROXY_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace org {
namespace zedroot {

class Douane_proxy
: public ::DBus::InterfaceProxy
{
public:

    Douane_proxy()
    : ::DBus::InterfaceProxy("org.zedroot.Douane")
    {
        connect_signal(Douane_proxy, NewActivityToBeValidated, _NewActivityToBeValidated_stub);
    }

public:

    /* properties exported by this interface */
        const std::string DaemonVersion() {
            ::DBus::CallMessage call ;
             call.member("Get"); call.interface("org.freedesktop.DBus.Properties");
            ::DBus::MessageIter wi = call.writer(); 
            const std::string interface_name = "org.zedroot.Douane";
            const std::string property_name  = "DaemonVersion";
            wi << interface_name;
            wi << property_name;
            ::DBus::Message ret = this->invoke_method (call);
            ::DBus::MessageIter ri = ret.reader ();
            ::DBus::Variant argout; 
            ri >> argout;
            return argout;
        };
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    void CreateRule(const std::string& rule_id, const bool& allow)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << rule_id;
        wi << allow;
        call.member("CreateRule");
        ::DBus::Message ret = invoke_method (call);
    }


public:

    /* signal handlers for this interface
     */
    virtual void NewActivityToBeValidated(const ::DBus::Struct< std::string, std::string, std::string, std::string >& activity) = 0;

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
    void _NewActivityToBeValidated_stub(const ::DBus::SignalMessage &sig)
    {
        ::DBus::MessageIter ri = sig.reader();

        ::DBus::Struct< std::string, std::string, std::string, std::string > activity;
        ri >> activity;
        NewActivityToBeValidated(activity);
    }
};

} } 
#endif //__dbusxx__org_zedroot_douane_proxy_h__PROXY_MARSHAL_H
